/* tslint:disable */
/* eslint-disable */
/**
 * Menu API
 * Burger menu API docs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BurgerOfTheDay
 */
export interface BurgerOfTheDay {
    /**
     * 
     * @type {number}
     * @memberof BurgerOfTheDay
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof BurgerOfTheDay
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BurgerOfTheDay
     */
    readonly price?: string;
    /**
     * 
     * @type {string}
     * @memberof BurgerOfTheDay
     */
    description?: string | null;
}

/**
 * Check if a given object implements the BurgerOfTheDay interface.
 */
export function instanceOfBurgerOfTheDay(value: object): value is BurgerOfTheDay {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BurgerOfTheDayFromJSON(json: any): BurgerOfTheDay {
    return BurgerOfTheDayFromJSONTyped(json, false);
}

export function BurgerOfTheDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): BurgerOfTheDay {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'price': json['price'] == null ? undefined : json['price'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function BurgerOfTheDayToJSON(json: any): BurgerOfTheDay {
    return BurgerOfTheDayToJSONTyped(json, false);
}

export function BurgerOfTheDayToJSONTyped(value?: Omit<BurgerOfTheDay, 'id'|'price'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

