/* tslint:disable */
/* eslint-disable */
/**
 * Menu API
 * Burger menu API docs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Menu } from './Menu';
import {
    MenuFromJSON,
    MenuFromJSONTyped,
    MenuToJSON,
    MenuToJSONTyped,
} from './Menu';

/**
 * 
 * @export
 * @interface Cart
 */
export interface Cart {
    price: any;
    /**
     * 
     * @type {number}
     * @memberof Cart
     */
    readonly id?: number;
    /**
     * 
     * @type {Menu}
     * @memberof Cart
     */
    menuItem?: Menu;
    /**
     * 
     * @type {number}
     * @memberof Cart
     */
    menuItemId: number;
    /**
     * 
     * @type {number}
     * @memberof Cart
     */
    quantity?: number;
    /**
     * 
     * @type {Array<Menu>}
     * @memberof Cart
     */
    readonly toppings?: Array<Menu>;
    /**
     * 
     * @type {Set<number>}
     * @memberof Cart
     */
    toppingIds?: Set<number>;
    /**
     * 
     * @type {string}
     * @memberof Cart
     */
    selectedOption?: string;
    /**
     * 
     * @type {string}
     * @memberof Cart
     */
    note?: string;
}

/**
 * Check if a given object implements the Cart interface.
 */
export function instanceOfCart(value: object): value is Cart {
    if (!('menuItemId' in value) || value['menuItemId'] === undefined) return false;
    return true;
}

export function CartFromJSON(json: any): Cart {
    return CartFromJSONTyped(json, false);
}

export function CartFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cart {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'menuItem': json['menu_item'] == null ? undefined : MenuFromJSON(json['menu_item']),
        'menuItemId': json['menu_item_id'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'toppings': json['toppings'] == null ? undefined : ((json['toppings'] as Array<any>).map(MenuFromJSON)),
        'toppingIds': json['topping_ids'] == null ? undefined : new Set(json['topping_ids']),
        'selectedOption': json['selected_option'] == null ? undefined : json['selected_option'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CartToJSON(json: any): Cart {
    return CartToJSONTyped(json, false);
}

export function CartToJSONTyped(value?: Omit<Cart, 'id'|'toppings'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'menu_item': MenuToJSON(value['menuItem']),
        'menu_item_id': value['menuItemId'],
        'quantity': value['quantity'],
        'topping_ids': value['toppingIds'] == null ? undefined : Array.from(value['toppingIds'] as Set<any>),
        'selected_option': value['selectedOption'],
        'note': value['note'],
    };
}

