/* tslint:disable */
/* eslint-disable */
/**
 * Menu API
 * Burger menu API docs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginCreateRequest
 */
export interface LoginCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginCreateRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginCreateRequest
     */
    password: string;
}

/**
 * Check if a given object implements the LoginCreateRequest interface.
 */
export function instanceOfLoginCreateRequest(value: object): value is LoginCreateRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginCreateRequestFromJSON(json: any): LoginCreateRequest {
    return LoginCreateRequestFromJSONTyped(json, false);
}

export function LoginCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginCreateRequestToJSON(json: any): LoginCreateRequest {
    return LoginCreateRequestToJSONTyped(json, false);
}

export function LoginCreateRequestToJSONTyped(value?: LoginCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

